#ifndef __MDR32FxQI_USB_HANDLERS_H
#define __MDR32FxQI_USB_HANDLERS_H

#include "MDR32FxQI_usb_default_handlers.h"
#include "usb_dfu.h"

#undef USB_DEVICE_HANDLE_RESET
#define USB_DEVICE_HANDLE_RESET  USB_DFU_Reset()

#undef USB_DEVICE_HANDLE_GET_DESCRIPTOR
#define USB_DEVICE_HANDLE_GET_DESCRIPTOR(wVALUE, wINDEX, wLENGTH)  USB_DFU_GetDescriptor(wVALUE, wINDEX, wLENGTH)

#undef USB_DEVICE_HANDLE_CLASS_REQUEST
#define USB_DEVICE_HANDLE_CLASS_REQUEST  USB_DFU_ClassRequest()

#undef USB_DEVICE_HANDLE_SET_CONFIGURATION
#define USB_DEVICE_HANDLE_SET_CONFIGURATION(wVALUE)  USB_DFU_SetConfiguration(wVALUE)

#endif /* __MDR32FxQI_USB_HANDLERS_H */
