name: Build Firmware

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Arm Toolchain and CMake
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-arm-none-eabi cmake build-essential

    - name: Build Bootloader
      run: |
        if [ -d "milander_bootloader/milandr-dfu-bootloader" ]; then cd milander_bootloader/milandr-dfu-bootloader; fi
        chmod +x ./build_and_flash.sh
        ./build_and_flash.sh --clean

    - name: Build Blink Example
      run: |
        if [ -d "milander_bootloader/milandr-dfu-bootloader" ]; then cd milander_bootloader/milandr-dfu-bootloader; fi
        chmod +x ./example_blink/build_and_flash.sh
        ./example_blink/build_and_flash.sh --clean
