name: Build DFU bootloader & blink example

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Arm Toolchain and CMake
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-arm-none-eabi cmake build-essential

    - name: Build Bootloader
      run: |
        chmod +x ./build_and_flash.sh
        ./build_and_flash.sh --clean

    - name: Build Blink Example
      run: |
        chmod +x ./example_blink/build_and_flash.sh
        ./example_blink/build_and_flash.sh --clean

    - name: Upload Bootloader Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: bootloader
        path: |
          build/milandr_dfu_bootloader.bin
          build/milandr_dfu_bootloader.hex
          build/milandr_dfu_bootloader

    - name: Upload Blink Example Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: blink-example
        path: |
          example_blink/build/blink.bin
          example_blink/build/blink.hex
          example_blink/build/blink

